import { Ionicons } from '@expo/vector-icons';
import { Linking, Pressable, View } from 'react-native';
import { Text } from '../AppTypography';
import { colors } from '../../constants/colors';
import { outfit } from '../../constants/typography';
import { webErpUrl } from '../../utils/webErpUrls';

type Props = {
  /** Portal `web_path` — interactive report page with filters. */
  webPath?: string;
  /** Full URL or site-relative path to a PDF stream (same as web ERP export). */
  pdfPathOrUrl?: string;
  compact?: boolean;
};

async function openUrl(url: string) {
  const can = await Linking.canOpenURL(url);
  if (can) await Linking.openURL(url);
}

export function ReportWebExportPanel({ webPath, pdfPathOrUrl, compact }: Props) {
  const webTrimmed = webPath?.trim() ?? '';
  const pdfResolved = pdfPathOrUrl?.trim()
    ? pdfPathOrUrl.startsWith('http')
      ? pdfPathOrUrl
      : webErpUrl(pdfPathOrUrl)
    : null;

  if (!webTrimmed && !pdfResolved) return null;

  const btnStyle = compact
    ? { paddingVertical: 12, borderRadius: 12, alignItems: 'center' as const, flexDirection: 'row' as const, justifyContent: 'center' as const, gap: 8 }
    : { paddingVertical: 14, borderRadius: 12, alignItems: 'center' as const, flexDirection: 'row' as const, justifyContent: 'center' as const, gap: 8 };

  return (
    <View style={{ marginTop: compact ? 12 : 20, gap: 10 }}>
      {pdfResolved ? (
        <Pressable
          onPress={() => void openUrl(pdfResolved)}
          style={[btnStyle, { backgroundColor: colors.primaryNavy }]}
        >
          <Ionicons name="document-text-outline" size={18} color="#fff" />
          <Text style={{ ...outfit('medium', 14), color: '#fff' }}>Open PDF (web ERP)</Text>
        </Pressable>
      ) : null}
      {webTrimmed ? (
        <Pressable
          onPress={() => void openUrl(webErpUrl(webTrimmed))}
          style={[
            btnStyle,
            pdfResolved
              ? { backgroundColor: colors.surface, borderWidth: 0.5, borderColor: colors.primaryNavy }
              : { backgroundColor: colors.primaryNavy },
          ]}
        >
          <Ionicons name="open-outline" size={18} color={pdfResolved ? colors.primaryNavy : '#fff'} />
          <Text style={{ ...outfit('medium', 14), color: pdfResolved ? colors.primaryNavy : '#fff' }}>
            {pdfResolved ? 'Full report in browser' : 'Open in web ERP'}
          </Text>
        </Pressable>
      ) : null}
      <Text style={{ ...outfit('regular', 11), color: colors.textMuted, lineHeight: 16 }}>
        PDFs are generated by the web ERP (same layout as desktop). Sign in in the browser if prompted; your mobile login does not share a session automatically.
      </Text>
    </View>
  );
}
