import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#eef2f8',
  },
  safeAuthed: {
    backgroundColor: '#07204a',
  },
  safeLogin: {
    backgroundColor: '#031336',
  },
  loginContainer: {
    flexGrow: 1,
    backgroundColor: '#031336',
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  loginShell: {
    flex: 1,
    justifyContent: 'center',
  },
  brandWrap: {
    alignItems: 'center',
    marginBottom: 16,
  },
  loginLogo: {
    width: 190,
    height: 50,
    marginBottom: 12,
  },
  loginTitle: {
    color: '#fff',
    fontSize: 28,
    fontFamily: 'Outfit_700Bold',
  },
  loginSubtitle: {
    color: '#9ab0db',
    marginTop: 4,
    fontFamily: 'Outfit_400Regular',
  },
  loginCard: {
    backgroundColor: '#0b204d',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#17356f',
  },
  loginInput: {
    backgroundColor: '#132e63',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: '#fff',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#244584',
    fontFamily: 'Outfit_500Medium',
  },
  inputLabel: {
    color: '#6e86b5',
    fontSize: 12,
    fontFamily: 'Outfit_700Bold',
    letterSpacing: 1,
    marginBottom: 6,
  },
  passwordWrap: {
    position: 'relative',
    marginBottom: 10,
  },
  loginInputPassword: {
    backgroundColor: '#132e63',
    borderRadius: 10,
    paddingLeft: 12,
    paddingRight: 42,
    paddingVertical: 11,
    color: '#fff',
    borderWidth: 1,
    borderColor: '#244584',
    fontFamily: 'Outfit_500Medium',
  },
  eyeButton: {
    position: 'absolute',
    right: 10,
    top: 8,
    padding: 4,
  },
  eyeText: {
    color: '#9ab0db',
    fontSize: 16,
  },
  loginButton: {
    marginTop: 6,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#00c8ff',
  },
  loginButtonText: {
    color: '#032046',
    fontFamily: 'Outfit_700Bold',
    fontSize: 16,
  },
  loginMetaRow: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rememberWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rememberText: {
    color: '#ffffff',
    marginLeft: 8,
    fontSize: 12,
    fontFamily: 'Outfit_400Regular',
  },
  checkbox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#4b67a0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: {
    backgroundColor: '#00c8ff',
    borderColor: '#00c8ff',
  },
  checkboxTick: {
    color: '#032046',
    fontWeight: '700',
    fontSize: 11,
  },
  forgotText: {
    color: '#8fd9ff',
    fontSize: 12,
    textDecorationLine: 'underline',
    fontFamily: 'Outfit_500Medium',
  },
  footerText: {
    marginTop: 18,
    textAlign: 'center',
    color: '#6f88b8',
    fontSize: 12,
    fontFamily: 'Outfit_400Regular',
  },
  footerLight: {
    textAlign: 'center',
    color: '#667085',
    fontSize: 12,
    marginTop: 8,
    fontFamily: 'Outfit_400Regular',
  },
  appShell: {
    flex: 1,
  },
  content: {
    padding: 14,
    gap: 10,
  },
  topHeader: {
    backgroundColor: '#07204a',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mainLogo: {
    width: 180,
    height: 52,
  },
  topHeaderButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0f2d63',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#1f4f9e',
  },
  topHeaderButtonText: {
    color: '#00c8ff',
    fontSize: 16,
    fontFamily: 'Outfit_700Bold',
  },
  headerCard: {
    backgroundColor: '#07204a',
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  helloText: {
    color: '#fff',
    fontFamily: 'Outfit_700Bold',
    fontSize: 18,
  },
  smallMuted: {
    color: '#94a7cc',
    fontFamily: 'Outfit_400Regular',
  },
  refreshPill: {
    backgroundColor: '#00c8ff',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  refreshPillText: {
    color: '#032046',
    fontFamily: 'Outfit_700Bold',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Outfit_700Bold',
    color: '#17233d',
    marginBottom: 10,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tile: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#e0e6f0',
    borderRadius: 10,
    padding: 10,
    backgroundColor: '#f9fbff',
  },
  tileLabel: {
    color: '#60708d',
    fontSize: 12,
    fontFamily: 'Outfit_400Regular',
  },
  tileValue: {
    color: '#17233d',
    fontFamily: 'Outfit_700Bold',
    marginTop: 4,
  },
  actionTile: {
    width: '48%',
    borderRadius: 10,
    padding: 10,
    backgroundColor: '#eff5ff',
    borderWidth: 1,
    borderColor: '#d8e7ff',
  },
  actionTitle: {
    color: '#173a77',
    fontFamily: 'Outfit_700Bold',
    marginBottom: 4,
  },
  actionHint: {
    color: '#5d6f91',
    fontSize: 12,
    fontFamily: 'Outfit_400Regular',
  },
  menuWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  menuChip: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#cfe0ff',
    backgroundColor: '#f4f8ff',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  menuChipText: {
    color: '#173a77',
    fontFamily: 'Outfit_600SemiBold',
    fontSize: 12,
  },
  menuChipAlt: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#d5dee9',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  moduleLead: {
    color: '#173a77',
    fontFamily: 'Outfit_700Bold',
    marginBottom: 6,
  },
  moduleBody: {
    color: '#5d6f91',
    fontFamily: 'Outfit_400Regular',
    marginBottom: 10,
  },
  approvalsSection: {
    marginTop: 12,
    gap: 8,
  },
  notificationsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  approvalsTitle: {
    color: '#17233d',
    fontFamily: 'Outfit_700Bold',
    fontSize: 14,
  },
  syncText: {
    color: '#667085',
    fontFamily: 'Outfit_400Regular',
    fontSize: 12,
  },
  approvalCard: {
    borderWidth: 1,
    borderColor: '#d9e4f4',
    borderRadius: 12,
    padding: 10,
    backgroundColor: '#fbfdff',
  },
  approvalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  approvalId: {
    color: '#1f4f9e',
    fontFamily: 'Outfit_700Bold',
    fontSize: 12,
  },
  approvalStatus: {
    color: '#5d6f91',
    fontFamily: 'Outfit_600SemiBold',
    fontSize: 12,
  },
  approvalType: {
    color: '#173a77',
    fontFamily: 'Outfit_600SemiBold',
  },
  approvalSubject: {
    color: '#17233d',
    fontFamily: 'Outfit_500Medium',
    marginTop: 2,
  },
  approvalOwner: {
    color: '#667085',
    fontFamily: 'Outfit_400Regular',
    fontSize: 12,
    marginTop: 2,
  },
  approvalNoteInput: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#d7e2f3',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#17233d',
    backgroundColor: '#ffffff',
    fontFamily: 'Outfit_400Regular',
    fontSize: 12,
    minHeight: 38,
  },
  notificationCard: {
    borderWidth: 1,
    borderColor: '#d9e4f4',
    borderRadius: 12,
    padding: 10,
    backgroundColor: '#ffffff',
  },
  notificationState: {
    fontFamily: 'Outfit_600SemiBold',
    fontSize: 12,
  },
  notificationUnread: {
    color: '#c13f3f',
  },
  notificationRead: {
    color: '#1a7f4d',
  },
  emptyStateCard: {
    borderWidth: 1,
    borderColor: '#e0e6f0',
    borderRadius: 12,
    padding: 12,
    backgroundColor: '#f8fbff',
  },
  emptyStateTitle: {
    color: '#17233d',
    fontFamily: 'Outfit_700Bold',
    marginBottom: 4,
  },
  emptyStateText: {
    color: '#5d6f91',
    fontFamily: 'Outfit_400Regular',
    marginBottom: 8,
  },
  approvalActions: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 8,
  },
  approveButton: {
    flex: 1,
    backgroundColor: '#e7f9ef',
    borderWidth: 1,
    borderColor: '#b8e9cc',
    borderRadius: 8,
    paddingVertical: 7,
    alignItems: 'center',
  },
  approveButtonText: {
    color: '#1a7f4d',
    fontFamily: 'Outfit_700Bold',
    fontSize: 12,
  },
  rejectButton: {
    flex: 1,
    backgroundColor: '#ffefef',
    borderWidth: 1,
    borderColor: '#ffcaca',
    borderRadius: 8,
    paddingVertical: 7,
    alignItems: 'center',
  },
  rejectButtonText: {
    color: '#c13f3f',
    fontFamily: 'Outfit_700Bold',
    fontSize: 12,
  },
  detailsButton: {
    flex: 1,
    backgroundColor: '#edf4ff',
    borderWidth: 1,
    borderColor: '#c8d9f8',
    borderRadius: 8,
    paddingVertical: 7,
    alignItems: 'center',
  },
  detailsButtonText: {
    color: '#1f4f9e',
    fontFamily: 'Outfit_700Bold',
    fontSize: 12,
  },
  approvalDetailCard: {
    borderWidth: 1,
    borderColor: '#d4e1f5',
    borderRadius: 12,
    padding: 10,
    backgroundColor: '#f8fbff',
  },
  approvalLineRow: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e7edf8',
  },
  leaveFormCard: {
    borderWidth: 1,
    borderColor: '#d9e4f4',
    borderRadius: 12,
    padding: 10,
    backgroundColor: '#fbfdff',
  },
  leaveTypeWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 6,
    marginBottom: 6,
  },
  leaveTypeChip: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d7e2f3',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#ffffff',
  },
  leaveTypeChipActive: {
    borderColor: '#1f4f9e',
    backgroundColor: '#edf4ff',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  highlight: {
    color: '#0088cc',
    fontFamily: 'Outfit_700Bold',
  },
  divider: {
    height: 1,
    backgroundColor: '#e4e8f0',
    marginVertical: 8,
  },
  meta: {
    color: '#42506a',
    marginBottom: 6,
    fontFamily: 'Outfit_400Regular',
  },
  primaryAction: {
    marginTop: 12,
    borderRadius: 10,
    backgroundColor: '#07204a',
    paddingVertical: 11,
    alignItems: 'center',
  },
  primaryActionText: {
    color: '#fff',
    fontFamily: 'Outfit_700Bold',
  },
  secondaryAction: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#c8d9f8',
    paddingVertical: 11,
    alignItems: 'center',
    backgroundColor: '#edf4ff',
  },
  secondaryActionText: {
    color: '#1f4f9e',
    fontFamily: 'Outfit_700Bold',
  },
  dangerAction: {
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: '#ef4d4d',
    paddingVertical: 11,
    alignItems: 'center',
  },
  dangerActionText: {
    color: '#fff',
    fontFamily: 'Outfit_700Bold',
  },
  disabled: {
    opacity: 0.5,
  },
  loader: {
    marginTop: 8,
  },
  bottomNav: {
    position: 'absolute',
    left: 10,
    right: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#07204a',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: '#12346f',
  },
  navItem: {
    alignItems: 'center',
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
  },
  navIcon: {
    color: '#8ca0c6',
    fontSize: 18,
    marginBottom: 3,
  },
  navLabel: {
    color: '#8ca0c6',
    fontSize: 12,
    fontFamily: 'Outfit_600SemiBold',
  },
  navActive: {
    color: '#00c8ff',
  },
  toastWrap: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: 12,
    zIndex: 40,
  },
  toastCard: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
  },
  toastInfo: {
    backgroundColor: '#edf4ff',
    borderColor: '#c8d9f8',
  },
  toastSuccess: {
    backgroundColor: '#e9f9ef',
    borderColor: '#b8e9cc',
  },
  toastError: {
    backgroundColor: '#fff0f0',
    borderColor: '#ffcaca',
  },
  toastText: {
    color: '#17233d',
    fontFamily: 'Outfit_600SemiBold',
    fontSize: 13,
  },
});
