import { Dimensions, StyleSheet } from 'react-native';
import { authTheme } from '../constants/authTheme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const KEYPAD_HORIZONTAL_PADDING = 16;
const KEYPAD_GAP = 10;
const KEYPAD_COLUMNS = 3;
const KEY_WIDTH =
  (SCREEN_WIDTH - KEYPAD_HORIZONTAL_PADDING * 2 - KEYPAD_GAP * (KEYPAD_COLUMNS - 1)) / KEYPAD_COLUMNS;

export const pinAuthStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: authTheme.bg,
  },
  headerScroll: {
    flex: 1,
  },
  headerScrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingTop: 8,
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  keypadSection: {
    paddingHorizontal: KEYPAD_HORIZONTAL_PADDING,
    paddingTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: authTheme.surfaceBorder,
    backgroundColor: authTheme.bg,
  },
  brandWrap: {
    width: '100%',
    alignItems: 'center',
  },
  loginLogo: {
    width: Math.min(SCREEN_WIDTH - 80, 240),
    height: 56,
    marginBottom: 24,
  },
  loginLogoFallback: {
    width: Math.min(SCREEN_WIDTH - 80, 240),
    alignItems: 'center',
    marginBottom: 24,
    paddingVertical: 6,
  },
  loginLogoFallbackTitle: {
    color: '#fff',
    fontSize: 22,
    letterSpacing: 1.2,
    fontFamily: 'Outfit_700Bold',
  },
  loginLogoFallbackTagline: {
    color: authTheme.textMuted,
    marginTop: 4,
    fontSize: 12,
    fontFamily: 'Outfit_400Regular',
  },
  securityIconOuter: {
    width: 96,
    height: 96,
    marginBottom: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  securityPhone: {
    width: 52,
    height: 78,
    borderRadius: 10,
    borderWidth: 2.5,
    borderColor: authTheme.textMuted,
    alignItems: 'center',
    paddingTop: 8,
  },
  securityPhoneScreen: {
    width: 38,
    height: 48,
    borderRadius: 4,
    backgroundColor: authTheme.fieldBg,
    borderWidth: 1,
    borderColor: authTheme.fieldBorder,
  },
  securityPhoneButton: {
    width: 14,
    height: 3,
    borderRadius: 2,
    backgroundColor: authTheme.textMuted,
    marginTop: 6,
  },
  securityLockBadge: {
    position: 'absolute',
    right: 8,
    bottom: 6,
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: authTheme.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: authTheme.surfaceBorder,
  },
  securityLockGlyph: {
    fontSize: 14,
  },
  pinHeading: {
    color: authTheme.accent,
    fontSize: 22,
    fontFamily: 'Outfit_600SemiBold',
    marginBottom: 8,
    textAlign: 'center',
  },
  welcomeText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Outfit_400Regular',
    marginBottom: 24,
    textAlign: 'center',
  },
  pinDotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
  },
  pinDot: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: authTheme.fieldBg,
    borderWidth: 2,
    borderColor: authTheme.fieldBorder,
    marginHorizontal: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinDotFilled: {
    backgroundColor: authTheme.surface,
    borderColor: authTheme.surfaceBorder,
  },
  pinDotActive: {
    borderColor: authTheme.accent,
    backgroundColor: authTheme.fieldBg,
  },
  pinDotCursor: {
    width: 2,
    height: 22,
    borderRadius: 1,
    backgroundColor: '#fff',
  },
  pinDotBullet: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    maxWidth: 320,
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  metaLink: {
    color: authTheme.link,
    fontSize: 13,
    fontFamily: 'Outfit_500Medium',
    textDecorationLine: 'underline',
  },
  biometricWrap: {
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  biometricButton: {
    width: 64,
    height: 64,
    borderRadius: 14,
    backgroundColor: authTheme.surface,
    borderWidth: 1,
    borderColor: authTheme.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  biometricButtonDisabled: {
    opacity: 0.45,
  },
  biometricHint: {
    color: authTheme.textMuted,
    fontSize: 13,
    fontFamily: 'Outfit_400Regular',
    textAlign: 'center',
  },
  keypad: {
    width: '100%',
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: KEYPAD_GAP,
  },
  keypadKey: {
    width: KEY_WIDTH,
    height: 52,
    borderRadius: 10,
    backgroundColor: authTheme.fieldBg,
    borderWidth: 1,
    borderColor: authTheme.fieldBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: KEYPAD_GAP / 2,
  },
  keypadKeyPressed: {
    backgroundColor: authTheme.surface,
    borderColor: authTheme.accent,
  },
  keypadKeyDisabled: {
    opacity: 0.45,
  },
  keypadKeySpacer: {
    width: KEY_WIDTH,
    height: 52,
    marginHorizontal: KEYPAD_GAP / 2,
  },
  keypadDigit: {
    color: '#fff',
    fontSize: 22,
    fontFamily: 'Outfit_500Medium',
  },
  keypadBackspace: {
    color: authTheme.textMuted,
    fontSize: 20,
    fontFamily: 'Outfit_500Medium',
  },
  setupHint: {
    color: authTheme.textMuted,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 19,
    fontFamily: 'Outfit_400Regular',
    marginBottom: 16,
    paddingHorizontal: 8,
    maxWidth: 320,
  },
  biometricToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: authTheme.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: authTheme.surfaceBorder,
    width: '100%',
    maxWidth: 320,
  },
  biometricToggleLabel: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Outfit_500Medium',
  },
  biometricToggleHint: {
    color: authTheme.textLabel,
    fontSize: 12,
    fontFamily: 'Outfit_400Regular',
    marginTop: 2,
  },
  biometricToggleButton: {
    width: 50,
    height: 28,
    borderRadius: 14,
    backgroundColor: authTheme.fieldBg,
    borderWidth: 1,
    borderColor: authTheme.fieldBorder,
    padding: 2,
    justifyContent: 'center',
  },
  biometricToggleButtonActive: {
    backgroundColor: authTheme.accent,
    borderColor: authTheme.accent,
  },
  biometricToggleKnob: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
  },
  biometricToggleKnobActive: {
    alignSelf: 'flex-end',
  },
  cancelLinkWrap: {
    marginTop: 4,
    marginBottom: 8,
  },
  footerText: {
    color: authTheme.footer,
    textAlign: 'center',
    fontSize: 12,
    fontFamily: 'Outfit_400Regular',
    marginTop: 10,
  },
});
